name: "Bump Versions"
description: "A GitHub Action to easily bump version files"
author: "Tommaso De Rossi"
branding:
  icon: "chevrons-up"
  color: "red"
inputs:
  version_file:
    description: "Version file to bump path"
    default: "VERSION"
    required: false
  prefix:
    description: "how to prefix the tag"
    default: ""
    required: false
  github_token:
    description: "the github token to push changes"
    required: false
  prerelease_tag:
    description: "The prerelease tag, for example alpha will give you the version `0.0.1-alpha.0`"
    required: false
  branch:
    description: "The branch to bump version in"
    required: false
    default: ""
  ignore:
    description: "Filenames to ignore, separated by commas"
    required: false
    default: ""
  skipCiMessageLocation:
    description: |
      Determines how to prevent another GitHub Actions run when `bump-version` creates a commit
      for the version update. The following options are supported:
      - `subject` (default): adds `[skip ci]` suffix to the end of the commit's subject line.
      - `trailer`: adds a `skip-checks: true` trailer to the commit.
    required: false
    default: "subject"
outputs:
  version:
    description: New version
  prefix:
    description: Prefix if set
runs:
  using: "node12"
  main: "lib/main.js"
# [bump]
# 2.0.57 // TODO regex match the rag

