#!/bin/sh
set -e
echo "running sed to replace [bump when prefix is: ...] with version ${VERSION}"
REPO_PATH=`git rev-parse --show-toplevel`

for FILE in `find $REPO_PATH -type f`; do
    LINE_NUMBERS=`sed -n -E "/\[bump when prefix is:[ ]+.*\].*/=" $FILE`
    if [ -n "$LINE_NUMBERS" ]; then
        for LINE_NUMBER in $LINE_NUMBERS; do
            PREFIX=`sed -n -E "${LINE_NUMBER}s/.*\[bump when prefix is:[ ]+(.*)\].*/\1/p" $FILE`
            echo "checking if line for prefix $PREFIX in $FILE is equal to $TAG_PREFIX"
            if [ "$PREFIX" = "$TAG_PREFIX" ]; then
                echo "found a line to replace content: $LINE_NUMBER in $FILE"
                let 'LINE_NUMBER++' || echo "let failed"
                echo "running" "${LINE_NUMBER}s/(.*)([0-9]+\.[0-9]+\.[0-9]+)(.*)/\1${VERSION}\3/g" "$FILE"
                sed -i -E "${LINE_NUMBER}s/(.*)([0-9]+\.[0-9]+\.[0-9]+)(.*)/\1${VERSION}\3/g" "$FILE" || echo "sed failed"
            fi
        done
    fi
done
